<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishAoT>true</PublishAoT>
  </PropertyGroup>

  <PropertyGroup>
    <MicrosoftAspNetCoreOpenApiOld>9.0.0-preview.6.24328.4</MicrosoftAspNetCoreOpenApiOld>
    <MicrosoftAspNetCoreOpenApiNew>9.0.0-rc.1.24408.8</MicrosoftAspNetCoreOpenApiNew>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="$(MicrosoftAspNetCoreOpenApiNew)" />
  </ItemGroup>

</Project>
